name: example
description: "A working example of a LayerX-generated app."
# Prevents accidental publication to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.0
  http: ^1.6.0
  shared_preferences: ^2.5.4
  logger: ^2.6.2
  google_fonts: ^6.3.3
  intl: ^0.20.2
  timezone: ^0.10.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  flutter_timezone: ^5.0.1
  firebase_messaging: ^16.0.0
  geolocator: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  layerx_generator:
    path: ../

flutter:
  uses-material-design: true
